import "./globals.css";
import { Inter } from "next/font/google";
import BaseLayout from "./components/BaseLayout";
import { BRAND_NAME } from "@/util/global";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: BRAND_NAME.toUpperCase(),
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='ko'>
      <head></head>
      <body className={inter.className}>
        <BaseLayout children={children} />
      </body>
    </html>
  );
}
